linter:
  rules:
    prefer_single_quotes: true
    unawaited_futures: true
    sort_constructors_first: true
    use_super_parameters: true
    use_colored_box: true
    use_decorated_box: true
    no_leading_underscores_for_local_identifiers: true
    require_trailing_commas: true
    avoid_futureor_void: false
    implementation_imports: true

analyzer:
  language:
    strict-raw-types: true
    strict-inference: true
    strict-casts: true
  errors:
    # By default, it's info level, we want warnings.
    todo: ignore
    unawaited_futures: warning
    prefer_single_quotes: warning
