name: module_injector
description: Provides dependency injection for the app
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  analyzer: ^13.3.0
  build: ^4.0.10
  flutter:
    sdk: flutter
  get_it: ^9.0.0
  glob: ^2.1.0
  meta: ^1.16.0
  source_gen: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true