name: portrai
description: "A portfolio app for Mayank Rai"
publish_to: 'none'
resolution: workspace

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cache: any
  collection: ^1.19.1
  core: any
  cupertino_icons: ^1.0.8
  design_system: any
  equatable: ^2.0.7
  error_reporter: any
  feature_flag: any
  firebase: any
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  go_router: ^17.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  log_reporter: any
  meta: ^1.16.0
  module_injector: any
  open_mail: ^1.2.1
  package_info_plus: ^10.0.0
  remote: any
  rxdart: ^0.28.0
  tracking: any
  url_launcher: ^6.3.1
  use_case: any

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  test: ^1.24.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/dashboard/portfolio.json
    - assets/dashboard/experiences.json
    - assets/dashboard/expertise.json
    - assets/dashboard/profile.json
    - assets/dashboard/projects.json
    - assets/dashboard/services.json
    - assets/dashboard/testimonials.json
