name: error_reporter
description: Provides reporting and handling errors for the app
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  core: any
  firebase: any
  flutter:
    sdk: flutter
  log_reporter: any
  meta: ^1.16.0
  module_injector: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true