name: remote
description: Provides all remote service for apis for the app
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  core: any
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  flutter:
    sdk: flutter
  module_injector: any
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true