import 'dart:async';
import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:glob/glob.dart';
import 'package:source_gen/source_gen.dart';

/// Generator that collects @Localizable annotated failures and generates
/// a centralized FailureTranslator class.
class FailureTranslatorBuilder implements Builder {
  @override
  Map<String, List<String>> get buildExtensions => {
    r'$lib$': ['generated/failure_translator.g.dart'],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final failures = <FailureInfo>[];

    // Scan all Dart files in the lib directory
    await for (final input in buildStep.findAssets(Glob('lib/**.dart'))) {
      if (!await buildStep.resolver.isLibrary(input)) continue;

      final library = await buildStep.resolver.libraryFor(input);
      final reader = LibraryReader(library);

      // Use TypeChecker to find annotated classes
      const checker = TypeChecker.fromUrl(
        'package:use_case/src/annotation/localizable.dart#Localizable',
      );

      for (final annotated in reader.annotatedWith(checker)) {
        try {
          final element = annotated.element;
          if (element is! ClassElement) continue;
          final annotation = annotated.annotation;

          // Extract class name
          final className = element.name ?? element.displayName;
          if (className.isEmpty) continue;

          // Extract localization key from annotation
          final key = annotation.read('key').stringValue;
          if (key.isEmpty) continue;

          // Get import path
          final lib = element.library;
          final importPath = lib.uri.scheme == 'package'
              ? lib.uri.toString()
              : 'package:${buildStep.inputId.package}/${input.path.replaceFirst('lib/', '')}';

          failures.add(
            FailureInfo(
              className: className,
              localizationKey: key,
              importPath: importPath,
            ),
          );
        } catch (e) {
          log.warning('Error processing ${input.path}: $e');
        }
      }
    }

    if (failures.isEmpty) {
      log.info('No @Localizable failures found');
      return;
    }

    // Sort for consistent output
    failures.sort((a, b) => a.className.compareTo(b.className));

    // Generate the translator code
    final code = _generateTranslatorCode(failures, buildStep.inputId.package);

    // Write the generated file
    final outputId = AssetId(
      buildStep.inputId.package,
      'lib/generated/failure_translator.g.dart',
    );

    await buildStep.writeAsString(outputId, code);

    log.info('Generated FailureTranslator with ${failures.length} failures');
  }

  String _generateTranslatorCode(
    List<FailureInfo> failures,
    String packageName,
  ) {
    // Get unique imports
    final imports = failures.map((f) => f.importPath).toSet().toList()..sort();

    final importStatements = imports.map((i) => "import '$i';").join('\n');

    // Generate switch cases
    final switchCases = failures
        .map((f) {
          return '      ${f.className}() => context.localizations.${f.localizationKey},';
        })
        .join('\n');

    // Generate fallback cases
    final fallbackCases = failures
        .map((f) {
          return "      ${f.className}() => '${_toHumanReadable(f.className)}',";
        })
        .join('\n');

    return '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: failure_translator_generator
// ignore_for_file: type=lint, unused_import

import 'package:flutter/material.dart';
import 'package:$packageName/l10n/l10n.dart';
import 'package:use_case/use_case.dart';
$importStatements

/// Auto-generated translator for all @Localizable failures.
///
/// This class is automatically generated by build_runner.
/// To regenerate, run: `flutter pub run build_runner build --delete-conflicting-outputs`
///
/// Do not modify this file manually.
class FailureTranslator {
  FailureTranslator._();

  /// Translates a failure to a localized user-friendly message.
  ///
  /// Uses pattern matching on failure types to determine the appropriate
  /// localized message from AppLocalizations.
  ///
  /// Falls back to a generic error message for unhandled failure types.
  static String translate(BuildContext context, Failure failure) {
    return switch (failure) {
$switchCases
      UnknownFailure() => context.localizations.errorGeneric,
      NoFailure() => '',
      _ => context.localizations.errorGeneric,
    };
  }

  /// Returns a fallback message for debugging when BuildContext is not available.
  ///
  /// This is useful for logging errors in places where BuildContext is not accessible,
  /// such as in BLoC layers or during error reporting.
  static String getFallbackMessage(Failure failure) {
    return switch (failure) {
$fallbackCases
      UnknownFailure() => 'Unknown error',
      NoFailure() => '',
      _ => 'Error: \${failure.runtimeType}',
    };
  }
}
''';
  }

  /// Converts a class name like "UserNotFoundFailure" to "User not found"
  String _toHumanReadable(String className) {
    // Remove "Failure" suffix
    final name = className.replaceFirst(RegExp(r'Failure$'), '');

    // Add spaces before capital letters
    return name
        .replaceAllMapped(RegExp(r'([A-Z])'), (match) => ' ${match.group(1)}')
        .trim();
  }
}

/// Information about a failure class annotated with @Localizable
class FailureInfo {
  FailureInfo({
    required this.className,
    required this.localizationKey,
    required this.importPath,
  });

  final String className;
  final String localizationKey;
  final String importPath;

  @override
  String toString() => '$className -> $localizationKey';
}
