name: core

on:
  pull_request:
    paths:
      - 'layer/core/**'
      - '.github/workflows/core.yaml'
      - '.github/actions/**'

jobs:
  analyze_and_test:
    name: Analyze & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Flutter Module
        uses: ./.github/actions/setup-flutter-module
        with:
          module-path: layer/core
      
      - name: Quality Checks
        uses: ./.github/actions/flutter-quality-checks
        with:
          module-path: layer/core
          collect-coverage: 'true'
          upload-coverage: 'true'
