name: design_system

on:
  pull_request:
    paths:
      - 'layer/design_system/**'
      - '.github/workflows/design_system.yaml'
      - '.github/actions/**'

jobs:
  analyze_and_test:
    name: Analyze & Test
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Flutter Module
        uses: ./.github/actions/setup-flutter-module
        with:
          module-path: layer/design_system
      
      - name: Quality Checks
        uses: ./.github/actions/flutter-quality-checks
        with:
          module-path: layer/design_system
          test-command: flutter test --dart-define=CI=true
          collect-coverage: 'true'
          upload-coverage: 'true'
