name: error_reporter

on:
  pull_request:
    paths:
      - 'layer/error_reporter/**'
      - '.github/workflows/error_reporter.yaml'
      - '.github/actions/**'

jobs:
  analyze_and_test:
    name: Analyze & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Flutter Module
        uses: ./.github/actions/setup-flutter-module
        with:
          module-path: layer/error_reporter
      
      - name: Quality Checks
        uses: ./.github/actions/flutter-quality-checks
        with:
          module-path: layer/error_reporter
          collect-coverage: 'true'
