name: feature_flag

on:
  pull_request:
    paths:
      - 'layer/feature_flag/**'
      - '.github/workflows/feature_flag.yaml'

jobs:
  analyze_and_test:
    name: Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.47.1

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        working-directory: layer/feature_flag
        run: flutter pub run build_runner build

      - name: Verify formatting
        working-directory: layer/feature_flag
        run: dart format --set-exit-if-changed .

      - name: Static analysis
        working-directory: layer/feature_flag
        run: dart analyze --fatal-infos .

      - name: Run tests
        working-directory: layer/feature_flag
        run: flutter test
