name: feature_flag

on:
  pull_request:
    paths:
      - 'layer/feature_flag/**'
      - '.github/workflows/feature_flag.yaml'
      - '.github/actions/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze_and_test:
    name: Analyze & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Flutter Module
        uses: ./.github/actions/setup-flutter-module
        with:
          module-path: layer/feature_flag
          run-codegen: 'true'
      
      - name: Quality Checks
        uses: ./.github/actions/flutter-quality-checks
        with:
          module-path: layer/feature_flag
          collect-coverage: 'true'
