name: firestore_export_import

on:
  pull_request:
    paths:
      - 'tool/firestore_export_import/**'
      - '.github/workflows/firestore_export_import.yaml'
      - '.github/actions/**'

jobs:
  analyze_and_test:
    name: Analyze & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Dart Module
        uses: ./.github/actions/setup-dart-module
        with:
          module-path: tool/firestore_export_import
      
      - name: Quality Checks
        uses: ./.github/actions/dart-quality-checks
        with:
          module-path: tool/firestore_export_import
          collect-coverage: 'true'
          upload-coverage: 'true'
